### ISSUE TITLE
Failed to start sandbox:   `npm start`  command does not work

### ISSUE THREAD

**Issue by SPSingh09** [nordible/zerodha-sandbox#2]
It throws an error:

code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\xxx\\zerodha-sandbox\\transpiled-build\\index.js'
  ]

I am not familiar with npm and nodjs, please help!

**Comment by xameeramir** [comment]
The error says that the build is not generated. If you run `tsc` the build will be generated for execution. If you get errors please do a Google search.
